
<div id="conteudo_baixo">
	

</div>
<div class="no-print downloads">
	<ul>
		<li><a href="/KBReader_v1.3.zip">Leitor de código de barras (download / windows)</a></li>
		<li><a href="https://play.google.com/store/apps/details?id=com.tecit.android.barcodekbd.demo" target="_blank">Leitor de código de barras (Google Play / android)</a></li>
		<li><a href="/salvar_permissao_camera.html" >Salvar permissão de camera para iPhone</a></li>
		<li><a href="/AplicativoJPA.apk" target="_blank">AplicativoJPA.apk - Android</a></li>
	</ul>
	
	
</div>
<?php echo $this->helpdesk(); ?>
</body>

<?php echo $this->inlineScript(); ?>

</html>