<style>
@media print{
	#header, .pagination, .buscar, #diferenca, .vender>input{
		display:none;
	}
	.vender{
		border-bottom: solid black 1px;
	}
	.tituloPag{
		display: block;
		font-size: 2em;
		margin-before: 0.67em;
		margin-after: 0.67em;
		margin-start: 0;
		margin-end: 0;
		font-weight: bold; 
		text-align: center;
	}
	.no-print>*{
		display: none;
	}
}
</style>

<?php
$auth = Zend_Auth::getInstance ();
$login = $auth->getIdentity();
$permissoes=array(1);
if($auth->hasIdentity() && in_array($login->nivel,$permissoes)){

	$this->headScript()
		->appendFile($this->baseUrl() . '/js/jquery/js/jquery-1.5.1.min.js','text/javascript')
		->appendFile($this->baseUrl() . '/js/jquery/js/jquery-ui-1.8.14.custom.min.js','text/javascript');
		
	$this->headLink()
		->appendStylesheet($this->baseUrl() . '/js/jquery/css/custom-theme/jquery-ui-1.8.14.custom.css');
	
		
	$this->headScript()->captureStart();
	?>
baseUrl = "<?php echo $this->baseUrl();?>";
$(function () {
	$(':input[type="number"]').change(function () { soma_qtd(); });
	var codigo_atual="";
	$(function () {
<?php if (!preg_match("/\d+/",$this->caixa)){?>
	$("#filtro").focus();
	setInterval(function() {
		//formata o codigo apos a leitura do cartao
		var id = $("#filtro").val();
		if (id.length > 8){
			 id = id.substr(id.length - 9,8);
			  $("#filtro").val(id);
			}
		}, 1200);
<?php }?>
var helpdesk = document.getElementById("helpdesk");
	helpdesk.style.display =  "none";
	
	soma_qtd();
	$("#pgdinheiro").keyup(function () {
		var novo_valor=$("#pgdinheiro").val().replace(/,/,".");
		novo_valor= novo_valor.replace(/('|"|-|´|`)/,"");
		$("#pgdinheiro").val(novo_valor);
		soma_qtd();
	});
	$("#pgcredito").keyup(function () {
		var novo_valor=$("#pgcredito").val().replace(/,/,".");
		novo_valor= novo_valor.replace(/('|"|-|´|`)/,"");
		$("#pgcredito").val(novo_valor);
		soma_qtd();
	});
	$("#pgdebito").keyup(function () {
		var novo_valor=$("#pgdebito").val().replace(/,/,".");
		novo_valor= novo_valor.replace(/('|"|-|´|`)/,"");
		$("#pgdebito").val(novo_valor);
		soma_qtd();
	});
	$("#pgcheque").keyup(function () {
		var novo_valor=$("#pgcheque").val().replace(/,/,".");
		novo_valor= novo_valor.replace(/('|"|-|´|`)/,"");
		$("#pgcheque").val(novo_valor);
		soma_qtd();
	});
	$("#pgdenario").keyup(function () {
		var novo_valor=$("#pgdenario").val().replace(/,/,".");
		novo_valor= novo_valor.replace(/('|"|-|´|`)/,"");
		$("#pgdenario").val(novo_valor);
		soma_qtd();
	});
<?php if (preg_match("/\d+/",$this->caixa)){?>
		$("form").submit(function () {
		//$("#buscar").trigger('change');
		//$(".qtd").trigger('blur');
		
		var total = parseFloat($(".vl_total").html()).toFixed(2);
		var creditos=0;
		//if (parseFloat($("span#creditos").html()))
		//	creditos += parseFloat($("span#creditos").html());
		if (parseFloat($("#pgdinheiro").val()))
			creditos += parseFloat($("#pgdinheiro").val());
		if (parseFloat($("#pgcredito").val()))
			creditos += parseFloat($("#pgcredito").val());
		if (parseFloat($("#pgdebito").val()))
			creditos += parseFloat($("#pgdebito").val());
		if (parseFloat($("#pgcheque").val()))
			creditos += parseFloat($("#pgcheque").val());
		if (parseFloat($("#pgdenario").val()))
			creditos += parseFloat($("#pgdenario").val());
		var	retorno = false;
		var saldo=creditos - total;	
		console.log(retorno);
		console.log(total);
		console.log(creditos);
		
		if ( creditos ==  0){ 
			alert('Nenhum valor de acerto de caixa digitado.');
		}
		else{
			$("#confirmar").attr("disabled",true);
			retorno= confirma_fechar_caixa(creditos.toFixed(2),$("span#descricaovendedor").html(),$("span#descricaocaixa").html());
		}
		if (retorno===false)
			$("#confirmar").attr("disabled",retorno);
		//return false;
		return retorno;
	});
<?php }?>
});
function soma_qtd(){
	var total = 0;
	if (parseFloat($("#pgdinheiro").val()))
		total += parseFloat($("#pgdinheiro").val());
	if (parseFloat($("#pgcredito").val()))
		total += parseFloat($("#pgcredito").val());
	if (parseFloat($("#pgdebito").val()))
		total += parseFloat($("#pgdebito").val());
	if (parseFloat($("#pgcheque").val()))
		total += parseFloat($("#pgcheque").val());
	if (parseFloat($("#pgdenario").val()))
		total += parseFloat($("#pgdenario").val());
	var saldo = total - $("span#total_geral").html().replace(/R../,"");	
	$("#diferenca").html(function () {
		if ( saldo >= 0)
			return '<span class="vl_total">' + saldo.toFixed(2) + '</span>';
		else
			return '<span class="vl_total_negativo">' + saldo.toFixed(2) + '</span>';
		});
	
	/*$("#confirmar").attr("disabled", function () {
		return (saldo >= 0 && creditos > 0 && total > 0) ? false : true;	
	});*/	
	}
});
<?php $this->headScript()->captureEnd() ?>
<div class="tituloPag"><?php echo (preg_match("/\d+/",$this->caixa)?"Fechamento de Caixa":"Relatorios")?></div>
<br>
<br>
<?php if (preg_match("/\d+/",$this->caixa)){?>

	<form action="<?php echo $this->url(array('action'=>'fechar','controller'=>'caixas','id_caixa'=>$this->caixa,'id_vendedor'=>$this->vendedor), null, true) ?>" method="POST">

<?php } else {?>

	<form action="<?php echo $this->url(array('action'=>'receitacaixa','controller'=>'relatorios')) ?>" method="get">
	<h2>Pesquisar Receita:</h2><input type="text" id="filtro" name="filtro" class="buscar" autocomplete="off" <?php echo "value='".(isset($_REQUEST['filtro'])?$_REQUEST['filtro']:"")."'";?> title="Voce pode pesquisar por cartao(CARTAO=1001), por caixa(CAIXA=1) ou por operador(VENDEDOR=10). Pode usar AND OR LIKE para combinar ">  
		<input type="submit" value="Buscar" class="buscar">

<?php }?>

<div class="clearfix"></div>

<br>
 <?php

    if(isset($this->paginator) && count($this->paginator) > 0){
    
    ?>
<table style="width: <?php echo (isset($this->caixa)?900:800)?>px;border: solid 1px #ccc ;">
    
        <tr>
        	<th class="rounded-company" style="width: 150px">Caixa</th>
        	<?php if (isset($this->caixa)){?>
        		<th class="rounded-company" style="width: 150px">Operador</th>
        	<?php }?>
            <th class="rounded-company" style="width: 250px">Forma de Pagamento</th>
            <th class="rounded-company" style="width: 150px">Qtd</th>
            <th class="rounded-company" style="width: 150px">Valor</th>
       
        </tr>
    
    <tbody>
   
        <?php
        	$tg=0;
        	$ultimo_caixa="";
        	foreach($this->paginator as $key){ ?>
        <tr><?php if ($key['Caixa'] != $ultimo_caixa){
        				$ultimo_caixa= $key['Caixa'];
        				$caixa_count=0;
        				if (isset($this->caixa)){?>
	        				<td class="listar-simples"><span id="descricaocaixa"><?php echo $key['Caixa']?></span></td>
							<td class="listar-simples"><span id="descricaovendedor"><?php echo $key['login']?></span></td>
        				<?php }else{?>
        				    <td class="listar-simples" ><?php echo $key['Caixa']; ?></td>
        				<?php }
        				}
        			else{
        				$caixa_count++;?>
        				<?php if (isset($this->caixa)){?>
        				<td>&nbsp;</td>
        				<?php }?>
        				<td>&nbsp;</td>
        	<?php 		}?>
            <td class="listar-simples"><?php echo $key['Forma']; ?></td>
            <td class="listar-simples"><?php echo $key['qtd']; ?><input type="hidden" name="Esperado[<?php echo $key['Forma']; ?>]" value="<?php echo $key['total']?>"></td>
            <td class="listar-simples" id="<?php echo preg_replace("/\W/","",$key['Forma']); ?>">R$ <?php printf("%.2f",$key['total']); ?></td>
        </tr>
        	
        <?php
        	$tg += $key['total']; 
    		} ?>
       		
       		<tr>
       		<td class="listar">&nbsp;</td>
            <td class="listar">&nbsp;</td>
            <td class="listar">TOTAL GERAL</td>
            <td class="listar"><span id="total_geral">R$ <?php printf("%.2f",$tg); ?></span></td>
            </tr>
       
    
    </tbody>
  
</table>
<br>
<?php if(preg_match("/\d+/",$this->caixa)){?>

	<table style="width: 450px;border: solid 1px #ccc ;">
		<tr>
	   <!--<th class="rounded-company" style="width: 300px">Código do produto</th> -->
	   <th  style="width: 280px" class="">Moeda</th>
	   <th  style="width: 200px" class="">Soma</th>
	   </tr>
	   <tbody>
	   <tr>
	   <td class="">Dinheiro</td>
	   <td class="vender"><input type="number" patern="\d{1,10}[\.\,]\d{2}" step="0.1" name="pgdinheiro" size="6" class="buscar" id="pgdinheiro" autocomplete="off" value=0></td>
	   </tr>
	   <tr>
	   <td class="">Cartao de Credito</td>
	   <td class="vender"><input type="number" patern="\d{1,10}[\.\,]\d{2}" step="0.1" name="pgcredito" size="6" class="buscar" id="pgcredito" autocomplete="off" value=0></td>
	   </tr>
	   <tr>
	   <td class="">Cartao de Debito</td>
	   <td class="vender"><input type="number" patern="\d{1,10}[\.\,]\d{2}" step="0.1" name="pgdebito" size="6" class="buscar" id="pgdebito" autocomplete="off" value=0></td>
	   </tr>
	   <tr>
	   <td class="">Cheque</td>
	   <td class="vender"><input type="number" patern="\d{1,10}[\.\,]\d{2}" step="0.1" name="pgcheque" size="6" class="buscar" id="pgcheque" autocomplete="off" value=0></td>
	   </tr>
	   	   <tr>
	   <td class=""><b>Total</b></td>
	   <td class="vender"><span id="diferenca">&nbsp;</span></td>
	   </tr>
	   </tbody>
	</table>
	<br>
	<input type="submit" value="Fechar o caixa" class="buscar">	


<?php }
     }
else {
	
	echo "<h2>Nenhum registro encontrado</h2>";
	
}
   ?>
   </form>
<br>

 <?php

    if(isset($this->paginator)){
  
echo $this->paginationControl($this->paginator, 'all', 'paginator_item.phtml');
    }}?>