<?php
$auth = Zend_Auth::getInstance ();
$login = $auth->getIdentity();
$permissoes=array(1);
if($auth->hasIdentity() && in_array($login->nivel,$permissoes)){

	$this->headScript()
		->appendFile($this->baseUrl() . '/js/jquery/js/jquery-1.5.1.min.js','text/javascript')
		->appendFile($this->baseUrl() . '/js/jquery/js/jquery-ui-1.8.14.custom.min.js','text/javascript');
		
	$this->headLink()
		->appendStylesheet($this->baseUrl() . '/js/jquery/css/custom-theme/jquery-ui-1.8.14.custom.css');
	
	?>
<div class="tituloPag"><?php echo (preg_match("/\d+/",$this->caixa)?"Fechamento de Caixa":"Relatorios")?></div>
<br>
<br>

	<form action="<?php echo $this->url(array('action'=>'receitacaixa','controller'=>'relatorios')) ?>" method="get">
<div class="clearfix"></div>

<br>
 <?php

    if(isset($this->paginator) && count($this->paginator) > 0){
    
    ?>
<table style="width: 800px;border: solid 1px #ccc ;">
    
        <tr>
            <th class="rounded-company" style="width: 250px">Forma de Pagamento</th>
            <th class="rounded-company" style="width: 150px">Qtd</th>
            <th class="rounded-company" style="width: 150px">Valor</th>
       
        </tr>
    
    <tbody>
   
        <?php
        $tg=0;
        foreach($this->paginator as $key){ ?>
            <td class="listar-simples"><?php echo $key['Forma']; ?></td>
            <td class="listar-simples"><?php echo $key['qtd']; ?></td>
            <td class="listar-simples" id="<?php echo preg_replace("/\W/","",$key['Forma']); ?>">R$ <?php printf("%.2f",$key['total']); ?></td>
        	</tr>
        	
        	<?php
        	$tg += $key['total']; 
    		} ?>
       		
       		<tr>
       		<td class="listar">&nbsp;</td>
            <td class="listar">TOTAL GERAL</td>
            <td class="listar"><span id="total_geral">R$ <?php printf("%.2f",$tg); ?></span></td>
            </tr>
       
    
    </tbody>
  
</table>
<br>
<?php
     }
else {
	
	echo "<h2>Nenhum registro encontrado</h2>";
	
}
   ?>
   </form>
<br>

 <?php

    if(isset($this->paginator)){
  
echo $this->paginationControl($this->paginator, 'all', 'paginator_item.phtml');
    }}?>