<?php
$auth = Zend_Auth::getInstance ();
$login = $auth->getIdentity();
$permissoes=array(1,2,4);
if($auth->hasIdentity() && in_array($login->nivel,$permissoes)){
	$this->headScript()
		->appendFile($this->baseUrl() . '/js/jquery/js/jquery-1.5.1.min.js','text/javascript')
		->appendFile($this->baseUrl() . '/js/jquery/js/jquery-ui-1.8.14.custom.min.js','text/javascript');
		
	$this->headLink()
		->appendStylesheet($this->baseUrl() . '/js/jquery/css/custom-theme/jquery-ui-1.8.14.custom.css');
	
		
	$this->headScript()->captureStart();
?>
baseUrl = "<?php echo $this->baseUrl(); ?>";

$(function () {
	var codigo_atual="";
	$("#filtro").focus();
	setInterval(function() {
		var id = $("#filtro").val();
		if (id.length > 8){
		  id = id.substr(id.length - 9,8);
		  $("#filtro").val(id);
			}
		}, 1200);
	});
 <?php $this->headScript()->captureEnd() ?>
 <div class="tituloPag">Relatorios</div>

<!--<a href="<?php echo $this->url(array('action'=>'new','controller'=>'Barraca'),null,1); ?>"> Incluir</a>
-->
<br>
<br>

<form action="<?php $this->url(array("controller"=>"Relatorios","action"=>"transacoesbarraca")) ?>" method="get">
<h2>Pesquisar Venda:</h2> <input type="text" name="filtro" id="filtro" class="buscar" autocomplete="off" value="<?php echo $this->filtro?>" title="Voce pode pesquisar por cartao, barraca, operador e status .Pode usar AND OR LIKE para combinar ex: CARTAO=1001 AND STATUS=0">  


<input type="submit" value="Buscar" class="buscar">

<div class="clearfix"></div>


<br>
 <?php

    if(isset($this->paginator) && count($this->paginator) > 0){
    ?>
<table style="width: 800px;border: solid 1px #ccc ;">
    
        <tr>
            <th class="rounded-company" style="width: 250px">Barraca</th>
            <th class="rounded-company" style="width: 250px">Produto</th>
            <th class="rounded-company" style="width: 100px">qtd</th>
            <th class="rounded-company" style="width: 200px">total</th>
       
        </tr>
    
    <tbody>
   
        <?php
        	$tvg=0;$tqg=0;
        	$tvp=0;$tqp=0;
        	$barraca=""; 
        	foreach($this->paginator as $key){
            	//if($barraca ==""){$barraca = $key['nome'];}
        		if($barraca != $key['nome'])
	        		{
	        		if ($barraca !=""){
		        		?>
		        		<tr>
			            <td class="listar-total" colspan=2><?php echo "TOTAL $barraca"; ?></td>
			            <td class="listar-total"><?php echo $tqp; ?></td>
			            <td class="listar-total">R$ <?php printf("%.2f",$tvp); ?></td>
			            </tr>
		        		<?php
	        		}
	        		$tvp=0;$tqp=0; 
	        		$barraca=$key['nome'];
	        		$barraca_count=0;
	        		}
	        	else{
	        		$barraca_count++;
	        		}
	        	$tvp += $key['total'];$tvg += $key['total'];
        		$tqp += $key['qtdv'];$tqg += $key['qtdv'];
	        	?>
	        	<tr>
	        	<td class="listar-simples"><?php echo ($barraca_count==0?$key['nome']:''); ?></td>
	            <td class="listar-simples"><?php echo $key['descricao']; ?></td>
	            <td class="listar-simples"><?php echo $key['qtdv']; ?></td>
	            <td class="listar-simples">R$ <?php printf("%.2f",$key['total']); ?></td>
		        </tr>
        		<?php
				 }
				 //imprime o ultimo total
	        	?>
				<tr>
					<td class="listar-total" colspan=2><?php echo "TOTAL $barraca"; ?></td>
					<td class="listar-total"><?php echo $tqp; ?></td>
					<td class="listar-total">R$ <?php printf("%.2f",$tvp); ?></td>
				</tr>
       		<tr>
            <td class="listar-total" colspan=2>TOTAL GERAL</td>
            <td class="listar-total"><?php echo $tqg; ?></td>
            <td class="listar-total">R$ <?php printf("%.2f",$tvg); ?></td>
            </tr>
       
       
    
    </tbody>
  
</table>
<?php }
else {
if ($login->nivel==1)	
	echo "<h2>Nenhum registro encontrado</h2>";
else
	echo "<h2>Cartão não informado ou não localizado!</h2>";
}
   ?>
<br>

 <?php


if (isset($this->paginator)){
	echo $this->paginationControl($this->paginator, 'all', 'paginator_item.phtml');
	}
}   