<?php 
$auth = Zend_Auth::getInstance ();
$login = $auth->getIdentity();
$permissoes=array(1,2,3,4);
if($auth->hasIdentity() && in_array($login->nivel,$permissoes)){
	$this->headScript()
		->appendFile($this->baseUrl() . '/js/jquery/js/jquery-1.5.1.min.js','text/javascript')
		->appendFile($this->baseUrl() . '/js/jquery/js/jquery-ui-1.8.14.custom.min.js','text/javascript');
		
	$this->headLink()
		->appendStylesheet($this->baseUrl() . '/js/jquery/css/custom-theme/jquery-ui-1.8.14.custom.css');
	
		
	$this->headScript()->captureStart();
?>
<script>
$(function () {
	$("#filtro").focus();
	setInterval(function() {
		//formata o codigo apos a leitura do cartao
		var id = $("#filtro").val();
		if (id.length > 8){
			 id = id.substr(id.length - 9,8);
			  $("#filtro").val(id);
			}
		}, 1200);
	});
</script>
 
 <div class="tituloPag">Relatorios</div>

<!--<a href="<?php echo $this->url(array('action'=>'new','controller'=>'Barraca'),null,1); ?>"> Incluir</a>
-->
<br>
<br>
<form action="<?php $this->url(array("controller"=>"Relatorios","action"=>"transacoes")) ?>" method="get">
<h2>Pesquisar Venda:</h2> <input class="buscar" autocomplete="off" <?php echo "value='".(isset($_REQUEST['filtro'])?$_REQUEST['filtro']:"")."'";?> type="text" id="filtro" name="filtro" title="Voce pode pesquisar por cartao, barraca, operador e status .Pode usar AND OR LIKE para combinar ex: CARTAO=1001 AND STATUS=0">  
<input type="submit" value="Buscar" class="buscar">

<div class="clearfix"></div>


<br>
 <?php

    if(count($this->paginator) > 0){
    ?>
<table style="width: 950px;border: solid 1px #ccc ;">
    
        <tr>
        	<th class="rounded-company" style="width: 150px">Data</th>
            <th class="rounded-company" style="width: 100px">Cartão</th>
            <th class="rounded-company" style="width: 150px">Portador</th>
            <th class="rounded-company" style="width: 200px">Barraca</th>
            <th class="rounded-company" style="width: 200px">Produto</th>
            <th class="rounded-company" style="width: 200px">Operador</th>
            <th class="rounded-company" style="width: 50px">qtd</th>
            <th class="rounded-company" style="width: 150px">Valor</th>
            <th class="rounded-company" style="width: 80px">Status</th>
       
        </tr>
    
    <tbody>
   		
        <?php foreach($this->paginator as $key): ?>
        <tr>
        	<td class="listar-simples"><?php echo preg_replace("/\d{4}-\d{2}-/","dia ",$key['dthr']); ?></td>
            <td class="listar-simples"><img src='/Produtos/bar/id/<?php echo $key['id_cartao']?>'></img></td>
            <td class="listar-simples"><?php echo $key['Portador']; ?></td>
            <td class="listar-simples"><?php echo $key['nome']; ?></td>
            <td class="listar-simples"><?php echo $key['descricao']; ?></td>
            <td class="listar-simples"><?php echo $key['login']; ?></td>
            <td class="listar-simples"><?php echo $key['qtd']; ?></td>
            <td class="listar-simples">R$ <?php printf("%.2f",$key['valor']); ?></td>
            <td class="listar-simples"><?php echo ($key['status']==0?'CANC':'OK'); ?></td>
            
            
           <!-- <td><a href="<?php //echo $this->url(array('action'=>'edit','controller'=>'Barraca','id_barracas'=>$key['id_barraca']),null,1); ?>">Editar</a>
             | <a href="<?php //echo $this->url(array('action'=>'delete','controller'=>'Barraca','id_barracas'=>$key['id_barraca']),null,1); ?>">Deletar</a> </td>
            -->
        </tr>
        <?php endforeach; ?>
       
       
       
    
    </tbody>
  
</table>
<?php }
else {
	
	echo "<h1>Nenhum registro encontrado</h1>";
	
}
   ?>
<br>

 <?php


  
echo $this->paginationControl($this->paginator, 'all', 'paginator_item.phtml');
}    