<?php 
$auth = Zend_Auth::getInstance ();
$login = $auth->getIdentity();
$permissoes=array(1,2,3,4);
if($auth->hasIdentity() && in_array($login->nivel,$permissoes)){
	$this->headScript()
		->appendFile($this->baseUrl() . '/js/jquery/js/jquery-1.5.1.min.js','text/javascript')
		->appendFile($this->baseUrl() . '/js/jquery/js/jquery-ui-1.8.14.custom.min.js','text/javascript')
		->appendFile($this->baseUrl() . '/js/zxing.js','text/javascript');
		
	$this->headLink()
		->appendStylesheet($this->baseUrl() . '/js/jquery/css/custom-theme/jquery-ui-1.8.14.custom.css');
	
		
	$this->headScript()->captureStart();
?>

 <div class="tituloPag"><?php echo $this->barraca." - VENDAS"; ?></div>

<!--<a class="listar" href="<?php echo $this->url(array('action'=>'new','controller'=>'Barraca'),null,1); ?>"> Incluir</a>
-->
<br>
<br>

<form action="<?php $this->url(array("controller"=>"cartao","action"=>"index")) ?>" method="get">
<h1>Pesquisar pelo código do cartão:</h1>
<img height=40 align="middle" src='/img/open_scan.JPG' id="barcode_button1" onclick="showScanner()"></img>
<img height=40 align="middle" src='/img/close_scan.JPG' id="barcode_button2" onclick="stopScanning()"></img>
<br/>
  <div id="select" class="select">
    <label for="videoSource">Câmera: </label><select id="videoSource"></select>
	<br/>
    <video muted autoplay id="video" playsinline="true"></video>
	<br/>
    <canvas id="pcCanvas" width="640" height="480" style="display: none; float: bottom;"></canvas>
    <canvas id="mobileCanvas" width="240" height="320" style="display: none; float: bottom;"></canvas>
  </div>
<input id="busca" type="text" name="busca" class="buscar" value="<?php echo (isset($_GET['id_cartao'])?$_GET['id_cartao']:'')?>">
<script>
var button1 = document.getElementById("barcode_button1");
var button2 = document.getElementById("barcode_button2");
var select = document.getElementById("select");
	button2.style.display =  "none";
	select.style.display =  "none";
	
var videoElement = document.querySelector('video');
var canvas = document.getElementById('pcCanvas');
var mobileCanvas = document.getElementById('mobileCanvas');
var ctx = canvas.getContext('2d');
var mobileCtx = mobileCanvas.getContext('2d');
var videoSelect = document.querySelector('select#videoSource');
var barcode_result = document.getElementById('busca');

var isScanning = false;
var videoWidth = 640;
var videoHeight = 480;
var mobileVideoWidth = 240, mobileVideoHeight = 320;
var isPC = true;

var ZXing = null;
var decodePtr = null;

var tick = function () {
  if (window.ZXing) {
    ZXing = ZXing();
    decodePtr = ZXing.Runtime.addFunction(decodeCallback);
  } else {
    setTimeout(tick, 10);
  }
};
tick();

var decodeCallback = function (ptr, len, resultIndex, resultCount) {
  var result = new Uint8Array(ZXing.HEAPU8.buffer, ptr, len);
  console.log(String.fromCharCode.apply(null, result));
  console.log(barcode_result);
  barcode_result.value = String.fromCharCode.apply(null, result);
};

// check devices
function browserRedirect() {
  var deviceType;
  var sUserAgent = navigator.userAgent.toLowerCase();
  var bIsIpad = sUserAgent.match(/ipad/i) == "ipad";
  var bIsIphoneOs = sUserAgent.match(/iphone os/i) == "iphone os";
  var bIsMidp = sUserAgent.match(/midp/i) == "midp";
  var bIsUc7 = sUserAgent.match(/rv:1.2.3.4/i) == "rv:1.2.3.4";
  var bIsUc = sUserAgent.match(/ucweb/i) == "ucweb";
  var bIsAndroid = sUserAgent.match(/android/i) == "android";
  var bIsCE = sUserAgent.match(/windows ce/i) == "windows ce";
  var bIsWM = sUserAgent.match(/windows mobile/i) == "windows mobile";
  if (bIsIpad || bIsIphoneOs || bIsMidp || bIsUc7 || bIsUc || bIsAndroid || bIsCE || bIsWM) {
    deviceType = 'phone';
  } else {
    deviceType = 'pc';
  }
  return deviceType;
}

if (browserRedirect() == 'pc') {
  isPC = true;
} else {
  isPC = false;
}

// stackoverflow: http://stackoverflow.com/questions/4998908/convert-data-uri-to-file-then-append-to-formdata/5100158
function dataURItoBlob(dataURI) {
  // convert base64/URLEncoded data component to raw binary data held in a string
  var byteString;
  if (dataURI.split(',')[0].indexOf('base64') >= 0)
    byteString = atob(dataURI.split(',')[1]);
  else
    byteString = unescape(dataURI.split(',')[1]);

  // separate out the mime component
  var mimeString = dataURI.split(',')[0].split(':')[1].split(';')[0];

  // write the bytes of the string to a typed array
  var ia = new Uint8Array(byteString.length);
  for (var i = 0; i < byteString.length; i++) {
    ia[i] = byteString.charCodeAt(i);
  }

  return new Blob([ia], {
    type: mimeString
  });
}


// scan barcode
function scanBarcode() {
  barcode_result.textContent = "";

  if (ZXing == null) {
    alert("Erro ao iniciar Leitor!");
    return;
  }

  var data = null,
    context = null,
    width = 640,
    height = 480,
    dbrCanvas = null;
	
  if (isPC) {
    context = ctx;
    width = videoWidth;
    height = videoHeight;
    dbrCanvas = canvas;
  } else {
    context = mobileCtx;
    width = mobileVideoWidth;
    height = mobileVideoHeight;
    dbrCanvas = mobileCanvas;
  }

  context.drawImage(videoElement, 0, 0, width, height);

  var vid = document.getElementById("video");
  //console.log("video width: " + vid.videoWidth + ", height: " + vid.videoHeight);
    
  var barcodeCanvas = document.createElement("canvas");  
  barcodeCanvas.width = vid.videoWidth;
  barcodeCanvas.height = vid.videoHeight;
  var barcodeContext = barcodeCanvas.getContext('2d');
  var imageWidth = vid.videoWidth, imageHeight = vid.videoHeight;
  barcodeContext.drawImage(videoElement, 0, 0, imageWidth, imageHeight);
  if (vid.videoWidth == 0){
	if (isScanning){
		setTimeout(scanBarcode, 100);
		return;
	}
  }
  // read barcode
  var imageData = barcodeContext.getImageData(0, 0, imageWidth, imageHeight);
  var idd = imageData.data;
  var image = ZXing._resize(imageWidth, imageHeight);
  console.time("decode barcode");
  for (var i = 0, j = 0; i < idd.length; i += 4, j++) {
    ZXing.HEAPU8[image + j] = idd[i];
  }
  var err = ZXing._decode_any(decodePtr);
  console.timeEnd('decode barcode');
  console.log("error code", err);
  if (err == -2) {
	  if (isScanning){
		setTimeout(scanBarcode, 100);
	  }
  }
}

// https://github.com/samdutton/simpl/tree/gh-pages/getusermedia/sources 
var videoSelect = document.querySelector('select#videoSource');

function showScanner() {	
	button2.style.display =  "block";
	select.style.display =  "block";
	button1.style.display =  "none";
	
	navigator.mediaDevices.enumerateDevices()
		.then(gotDevices).then(getStream).catch(handleError);  
  
  setTimeout(function(){	  
  
	  if (isPC) {
		canvas.style.display = 'none';
	  } else {
		mobileCanvas.style.display = 'none';
	  }
	  isScanning = true;
	  scanBarcode();
	}, 1000);
}

videoSelect.onchange = getStream;

function gotDevices(deviceInfos) {
  while (videoSelect.firstChild) {
    videoSelect.removeChild(videoSelect.firstChild);
  }
  for (var i = deviceInfos.length - 1; i >= 0; --i) {
    var deviceInfo = deviceInfos[i];
    var option = document.createElement('option');
    option.value = deviceInfo.deviceId;
    if (deviceInfo.kind === 'videoinput') {
      option.text = deviceInfo.label || 'camera ' +
        (videoSelect.length + 1);
      videoSelect.appendChild(option);
    } else {
      //console.log('Found one other kind of source/device: ', deviceInfo);
    }
  }
}
function stopScanning() {	
	button1.style.display =  "block";
	button2.style.display =  "none";
	select.style.display =  "none";
	isScanning = false;
	if (window.stream) {
		window.stream.getTracks().forEach(function(track) {
		  track.stop();
		});
	}
}

function getStream() {
  if (window.stream) {
    window.stream.getTracks().forEach(function(track) {
      track.stop();
    });
  }

  var constraints = {
    video: {
      deviceId: {exact: videoSelect.value}
    }
  };

  navigator.mediaDevices.getUserMedia(constraints).
    then(gotStream).catch(handleError);
}

function gotStream(stream) {
  window.stream = stream; // make stream available to console
  videoElement.srcObject = stream;
}

function handleError(error) {
  console.log('Erro: ', error);
}
</script>
<script>
baseUrl = "<?php echo $this->baseUrl(); ?>";
$(function () {
    $('form').submit(function(){
        $("#busca").trigger('change');
        return false;
    })
	$("#busca").focus();
	$("#busca").change(function () {
		var id = $(this).val();
		if (id.length > 8){
			id = id.substr(id.length - 9,8);
			window.location.href = baseUrl + '/relatorios/vendasbarraca/id_barracas/'+ <?php echo ($this->id_barraca) ? $this->id_barraca : 0 ?> + '/id_cartao/' + id;
		};

        if (id.match(/\-\d+/)){
            window.location.href = baseUrl + '/relatorios/vendasbarraca/id_barracas/0/id_cartao/' + id;
        }
	});
	setInterval(function() {
		var id = $("#busca").val();
		if (id.length > 8){
			$("#busca").trigger('change');
			}
		}, 1500);
});	
</script>

<div class="clearfix"></div>

<div id="resultado_pesquisa">
<br>
 <?php
 if(isset($this->paginator) && count($this->paginator) > 0 ){
	$auth = Zend_Auth::getInstance ();
	$login = $auth->getIdentity();
    
    ?>
<table style="width: 950px;border: solid 1px #ccc ;">
    
        <tr>
            <th class="rounded-company" style="width: 300px">Data</th>
            <th class="rounded-company" style="width: 100px">Cart&atilde;o</th>
            <th class="rounded-company" style="width: 300px">Portador</th>
            <th class="rounded-company" style="width: 300px">Produto</th>
            <th class="rounded-company" style="width: 50px">Qtd</th>
            <th class="rounded-company" style="width: 190px">Valor</th>
            <th class="rounded-company" style="width: 250px">Operador</th>
            <th class="rounded-company" style="width: 100px">Status</th>
            <?php if($login->nivel == 1){?>
            <th class="rounded-company" style="width: 100px">A&ccedil;&atilde;o</th>
            <?php }?>       
        </tr>
    
    <tbody>
   
        <?php 

        foreach($this->paginator as $key): ?>
        <tr>
            <td class="listar-simples"><?php echo $key['dthr']; ?></td>
            <td class="listar-simples">
            <?php if($key['id_cartao']>0){ ?>
                <img src='/Produtos/bar/id/<?php echo $key['id_cartao']?>'></img>
            <?php }else{
                echo 'Venda direta no caixa';
                } ?>
            </td>
            <td class="listar-simples"><?php echo $key['portador']; ?></td>
            <td class="listar-simples"><?php echo $key['descricao']; ?></td>
            <td class="listar-simples"><?php echo $key['qtd']; ?></td>
            <td class="listar-simples">R$ <?php printf("%.2f",$key['total']); ?></td>
            <td class="listar-simples"><?php echo $key['login']; ?></td>
            <td class="listar-simples"><?php echo ($key['status']==0?'CANC':'OK'); ?></td>
            <?php if($login->nivel == 1 || $login->nivel == 4){?>
            <td class="listar-simples">
            <?php 	echo '<a href="' . $this->url(array('action'=>'estorno','controller'=>'Vendas','id_venda'=>$key['id_venda'],'id_barraca'=>$key['barraca'], 'id_cartao'=>$key['id_cartao']),null,1); 
					$msg="'".$key['id_cartao']."','".$key['portador']."','".$key['descricao']." -> Quantidade: ".$key['qtd']."','".$key['total']."'"; 
            echo ($key['status']==1?'"onclick="return confirma_estorno_venda('.$msg.', this)"> Cancelar':'">')."</a> | "; 
			echo '<a href="' . $this->url(array('action'=>'estornounico','controller'=>'Vendas','id_venda'=>$key['id_venda'],'qtd'=>$key['qtd'],'valor'=>$key['valor'],'id_barraca'=>$key['barraca'], 'id_cartao'=>$key['id_cartao']),null,1); 
			$msg="'".$key['id_cartao']."','".$key['portador']."','".$key['descricao']."','".$key['valor']."'";
            echo ($key['qtd']>1? ( $key['status']==1?'"onclick="return confirma_estorno_venda('.$msg.', this)"> Cancelar Unitário':'">'):'">')."</a>";
			?>
            </td>
  			<?php }?>       
        </tr>
        <?php endforeach; ?>
       
       
       
    
    </tbody>
  
</table>

<?php }
else {
	
	echo "<h2>Nenhum registro encontrado</h2>";
	
}
   ?>
</div>
<br>

 <?php
 if(isset($this->paginator)){
	echo $this->paginationControl($this->paginator, 'all', 'paginator_item.phtml');
 	}
}
	?>

  

    