<?php
$auth = Zend_Auth::getInstance ();
$login = $auth->getIdentity();
$permissoes=array(1,4);
if($auth->hasIdentity() && in_array($login->nivel,$permissoes)){?>
 
 <div class="tituloPag">Produtos</div>

<a class="listar" href="<?php echo $this->url(array('action'=>'new','controller'=>'Produtos'),null,1); ?>">Incluir</a>
<br>
<?php 
if (isset($this->paginator))
echo $this->paginationControl($this->paginator, 'all', 'paginator_item.phtml');
?>
<br>


<div class="clearfix"></div>


<br>
 <?php

    if(count($this->paginator) > 0){
    
    ?>
<table style="width: 900px;border: solid 1px #ccc ;">
    
        <tr>
            <th class="rounded-company" style="width: 200px">Barraca</th>
            <th class="rounded-company" style="width: 200px">Produto</th>
            <th class="rounded-company" style="width: 100px">Estoque</th>
            <th class="rounded-company" style="width: 100px">Custo</th>
            <th class="rounded-company" style="width: 120px">Valor</th>
            <th class="rounded-company" style="width: 200px">Ações</th>
        </tr>
    
    <tbody>
   
        <?php foreach($this->paginator as $key): ?>
        <tr>
			<td class="listar-simples"><?php echo $key['nome']; ?></td>
            <td class="listar-simples"><?php echo $key['descricao']; ?></td>
            <td class="listar-simples"><?php echo $key['estoque']; ?></td>
            <td class="listar-simples"><?php echo "R$ ";printf("%.2f",$key['custo']); ?></td>
            <td class="listar-simples"><?php echo "R$ ";printf("%.2f",$key['valor']); ?></td>
            <td class="listar-simples"><a href="<?php echo $this->url(array('action'=>'edit','controller'=>'Produtos','id_produtos'=>$key['id_produtos']),null,1); ?>">Editar</a>
             | <a href="<?php echo $this->url(array('action'=>'delete','controller'=>'Produtos','id_produtos'=>$key['id_produtos']),null,1); ?>">Deletar</a> </td>
            
        </tr>
        <?php endforeach; ?>
       
       
       
    
    </tbody>
  
</table>
<?php }
else {
	
	echo "<h1>Nenhum registro encontrado</h1>";
	
}
   ?>
<br>

 <?php

 if (isset($this->paginator))
echo $this->paginationControl($this->paginator, 'all', 'paginator_item.phtml');

}?>