<?php 
$auth = Zend_Auth::getInstance ();
$login = $auth->getIdentity();
$permissoes=array(1,2,3,4);
if($auth->hasIdentity() && in_array($login->nivel,$permissoes)){
	$this->headScript()
		->appendFile($this->baseUrl() . '/js/jquery/js/jquery-1.5.1.min.js','text/javascript')
		->appendFile($this->baseUrl() . '/js/jquery/js/jquery-ui-1.8.14.custom.min.js','text/javascript')
		->appendFile($this->baseUrl() . '/js/zxing.js','text/javascript');
		
	$this->headLink()
		->appendStylesheet($this->baseUrl() . '/js/jquery/css/custom-theme/jquery-ui-1.8.14.custom.css');
	
		
	$this->headScript()->captureStart(); ?>
	baseUrl = "<?php echo $this->baseUrl(); ?>";
<?php $this->headScript()->captureEnd() ?>

<script>
$(function () {
	var codigo_atual="";
	$("#buscar").focus();
	$("#buscar").focus(function(){
		$('span#nome').html("&nbsp;");
		$('span#creditos').html("&nbsp;");
		});
	$("#buscar").keydown(function () {
		$('span#nome').html("&nbsp;");
		$('span#creditos').html("&nbsp;");
		$('#alerta').html("<h3>&nbsp;</h3>");
	});
	setInterval(function() {
		//verifica se o leitor substituiu o codigo sem mudar de campo(ipad)
		if($("#buscar").val() != codigo_atual){
			codigo_atual= $("#buscar").val();
			$("#buscar").trigger('change');
			$('#alerta').html("<h3>&nbsp;</h3>");
			}
		//verifica se o leitor copiou o codigo mas ainda nao pesquisou o codigo(ipad)
		if(! parseFloat($("span#creditos").html()) && $("#buscar").val().length > 7 ){
			$("#buscar").trigger('change');
			$('#alerta').html("<h3>&nbsp;</h3>");
			$("#confirmar").attr("disabled",true);
			}
		//apaga o codigo digitado que nao existe no banco
		if( !$("span#creditos").html().match(/\d+/) && $("#buscar").val().length > 7 ){
			$("#buscar").val('ERR');
			$('#alerta').html("<h3>&nbsp;</h3>");
			$("#confirmar").attr("disabled",true);
			}
		}, 1500);
	$(".qtd").keyup(function () {
		soma_qtd();
	});
	$("#buscar").change(function () {
		var id = $(this).val();
		if (id.length > 8){
		  id = id.substr(id.length - 9,8);
		  $("#buscar").val(id);
		  $.ajax({
			url: baseUrl + '/cartao/portador/id/' + id,
			dataType: 'json',
			async    : false,
		  	success: function(data) {
		    	$('span#nome').html(data[0].descricao);
		    	$('span#creditos').html(parseFloat(data[0].creditos).toFixed(2));
		    	soma_qtd();
		    	//$(".item").find('input').val('');
		    	//alert('Load was performed.');
			}
		});
		}
	});
	
	$("form").submit(function () {
		$("#buscar").trigger('change');
		$(".qtd").trigger('blur');
		
		var total = parseFloat($(".vl_total").html()).toFixed(2);
		var	creditos = parseFloat($("span#creditos").html()).toFixed(2);
		var	retorno = false;
		var saldo=creditos - total;	
		console.log(retorno);
		console.log(total);
		console.log(creditos);
		
		if (saldo < 0 && total > 0){ 
			alert('Saldo insuficiente R$ '+ saldo.toFixed(2));
		}
		else{
			$("#confirmar").attr("disabled",true);
			retorno= confirma_venda(total,$("#buscar").val(),$("span#nome").html(),saldo.toFixed(2));
		}
		if (retorno===false)
			$("#confirmar").attr("disabled",retorno);
		//return false;
		return retorno;
	});
});
function increment_qtd(campo,acao,numero){
	//alert (campo+ ' '+ acao);
	if(! parseFloat($("span#creditos").html())){
		$("#buscar").trigger('change');
		}
	var x=document.getElementById(campo).value;
	if(acao=='less' && x > numero - 1){
		document.getElementById(campo).value= x - numero;
		$(".qtd").trigger('blur');
		soma_qtd();
		}
	if(acao=='plus'){
		var x=document.getElementById(campo).value;
		//alert('ok');
		document.getElementById(campo).value=parseInt(x) + numero;
		soma_qtd();
		}
		};
		
function soma_qtd(){
	var item = $('.item');
	var qtd = [];
	var valor = [];
	var total = 0;
			
	item.find('.valor').each(function () {
		valor.push($(this).val());
	});
	item.find('.qtd').each(function () {
		var tmp = $(this).val();
		if (tmp > 100)
			tmp = 100
		if (tmp < 0)
			tmp = 0;
		qtd.push(tmp);
		$(this).val(tmp);
	});
		
	$.each(qtd,function (i,val) {
		if (val != '' && val > 0){
			total += val * valor[i];
		}
	});
		
	$("#valor_total").html(function () {
		return '<span class="vl_total">' + total.toFixed(2) + '</span>';
	});
	$("#saldo_remanescente").html(function () {
		var saldo= parseFloat($("span#creditos").html()) - total;
		if (saldo > 0)
			return '<span class="vl_total">' + saldo.toFixed(2) + '</span>';
		else
			return '<span class="vl_total_negativo">' + saldo.toFixed(2) + '</span>';
		});
	
	$("#confirmar").attr("disabled", function () {
		var creditos = parseFloat($("span#creditos").html()).toFixed(2);
		return (total <= creditos && total > 0) ? false : true;	
	});
};

</script>
 
 <div class="tituloPag"><?php echo $this->nome;?></div>

<br>



<div id="conteudo_tabela" class="#conteudo_centro">
<br>
 <?php
 $i=0;
 if(isset ($this->paginator) && count($this->paginator) > 0 && is_array($_SESSION['BARRACAS']) && in_array($this->nome,$_SESSION['BARRACAS'])){
   	
    ?>
 <form method="post" action="../../../Vendas/salvavenda">

<img height=40 align="middle" src='/img/open_scan.JPG' id="barcode_button1" onclick="showScanner()"></img>
<img height=40 align="middle" src='/img/close_scan.JPG' id="barcode_button2" onclick="stopScanning()"></img>
<br/>
  <div id="select" class="select">
    <label for="videoSource">Câmera: </label><select id="videoSource"></select>
	<br/>
    <video muted autoplay id="video" playsinline="true"></video>
	<br/>
    <canvas id="pcCanvas" width="640" height="480" style="display: none; float: bottom;"></canvas>
    <canvas id="mobileCanvas" width="240" height="320" style="display: none; float: bottom;"></canvas>
  </div>


<div id="container">
	<p>
	<table style="width: 750px;border: solid 1px #ccc ; text-align:left;">
	<tr><th style="width: 360px" >
		

			<label>Cartão</label><br>
        	<input type="number" name="busca" class="buscar" id="buscar" autocomplete="off">
	    </th>
        <div id="container-portador">
        <th style="width: 200px" >
        <div class="span-creditos">Credito (R$)<br><span id="creditos">&nbsp;</span></div></th>
        <th>
        <div class="span-portador">Portador<br><span id="nome">&nbsp;</span></div></th>
        </div>
        <tr>
       </table>
	</p>
</div>

<script>
var button1 = document.getElementById("barcode_button1");
var button2 = document.getElementById("barcode_button2");
var select = document.getElementById("select");
	button2.style.display =  "none";
	select.style.display =  "none";
	
var videoElement = document.querySelector('video');
var canvas = document.getElementById('pcCanvas');
var mobileCanvas = document.getElementById('mobileCanvas');
var ctx = canvas.getContext('2d');
var mobileCtx = mobileCanvas.getContext('2d');
var videoSelect = document.querySelector('select#videoSource');
var barcode_result = document.getElementById('buscar');

var isScanning = false;
var videoWidth = 640;
var videoHeight = 480;
var mobileVideoWidth = 240, mobileVideoHeight = 320;
var isPC = true;

var ZXing = null;
var decodePtr = null;

var tick = function () {
  if (window.ZXing) {
    ZXing = ZXing();
    decodePtr = ZXing.Runtime.addFunction(decodeCallback);
  } else {
    setTimeout(tick, 10);
  }
};
tick();

var decodeCallback = function (ptr, len, resultIndex, resultCount) {
  var result = new Uint8Array(ZXing.HEAPU8.buffer, ptr, len);
  console.log(String.fromCharCode.apply(null, result));
  console.log(barcode_result);
  barcode_result.value = String.fromCharCode.apply(null, result);
  stopScanning();
};

// check devices
function browserRedirect() {
  var deviceType;
  var sUserAgent = navigator.userAgent.toLowerCase();
  var bIsIpad = sUserAgent.match(/ipad/i) == "ipad";
  var bIsIphoneOs = sUserAgent.match(/iphone os/i) == "iphone os";
  var bIsMidp = sUserAgent.match(/midp/i) == "midp";
  var bIsUc7 = sUserAgent.match(/rv:1.2.3.4/i) == "rv:1.2.3.4";
  var bIsUc = sUserAgent.match(/ucweb/i) == "ucweb";
  var bIsAndroid = sUserAgent.match(/android/i) == "android";
  var bIsCE = sUserAgent.match(/windows ce/i) == "windows ce";
  var bIsWM = sUserAgent.match(/windows mobile/i) == "windows mobile";
  if (bIsIpad || bIsIphoneOs || bIsMidp || bIsUc7 || bIsUc || bIsAndroid || bIsCE || bIsWM) {
    deviceType = 'phone';
  } else {
    deviceType = 'pc';
  }
  return deviceType;
}

if (browserRedirect() == 'pc') {
  isPC = true;
} else {
  isPC = false;
}

// stackoverflow: http://stackoverflow.com/questions/4998908/convert-data-uri-to-file-then-append-to-formdata/5100158
function dataURItoBlob(dataURI) {
  // convert base64/URLEncoded data component to raw binary data held in a string
  var byteString;
  if (dataURI.split(',')[0].indexOf('base64') >= 0)
    byteString = atob(dataURI.split(',')[1]);
  else
    byteString = unescape(dataURI.split(',')[1]);

  // separate out the mime component
  var mimeString = dataURI.split(',')[0].split(':')[1].split(';')[0];

  // write the bytes of the string to a typed array
  var ia = new Uint8Array(byteString.length);
  for (var i = 0; i < byteString.length; i++) {
    ia[i] = byteString.charCodeAt(i);
  }

  return new Blob([ia], {
    type: mimeString
  });
}


// scan barcode
function scanBarcode() {
  barcode_result.textContent = "";

  if (ZXing == null) {
    alert("Erro ao iniciar Leitor!");
    return;
  }

  var data = null,
    context = null,
    width = 640, 
    height = 480,
    dbrCanvas = null;

  if (isPC) {
    context = ctx;
    width = videoWidth;
    height = videoHeight;
    dbrCanvas = canvas;
  } else {
    context = mobileCtx;
    width = mobileVideoWidth;
    height = mobileVideoHeight;
    dbrCanvas = mobileCanvas;
  }

  context.drawImage(videoElement, 0, 0, width, height);

  var vid = document.getElementById("video");
  //console.log("video width: " + vid.videoWidth + ", height: " + vid.videoHeight);
  var barcodeCanvas = document.createElement("canvas");
  barcodeCanvas.width = vid.videoWidth;
  barcodeCanvas.height = vid.videoHeight;
  var barcodeContext = barcodeCanvas.getContext('2d');
  var imageWidth = vid.videoWidth, imageHeight = vid.videoHeight;
  barcodeContext.drawImage(videoElement, 0, 0, imageWidth, imageHeight);
  if (vid.videoWidth == 0){
	  if (isScanning){
		setTimeout(scanBarcode, 100);
		return;
	  }
  }
  // read barcode
  var imageData = barcodeContext.getImageData(0, 0, imageWidth, imageHeight);
  var idd = imageData.data;
  var image = ZXing._resize(imageWidth, imageHeight);
  console.time("decode barcode");
  for (var i = 0, j = 0; i < idd.length; i += 4, j++) {
    ZXing.HEAPU8[image + j] = idd[i];
  }
  var err = ZXing._decode_any(decodePtr);
  console.timeEnd('decode barcode');
  console.log("error code", err);
  if (err == -2) {
	  if (isScanning){
		setTimeout(scanBarcode, 100);
	  }
  }
}
// https://github.com/samdutton/simpl/tree/gh-pages/getusermedia/sources 
var videoSelect = document.querySelector('select#videoSource');

function showScanner() {	
	button2.style.display =  "block";
	select.style.display =  "block";
	button1.style.display =  "none";
	
	navigator.mediaDevices.enumerateDevices()
		.then(gotDevices).then(getStream).catch(handleError);  
  
  setTimeout(function(){	  
  
	  if (isPC) {
		canvas.style.display = 'none';
	  } else {
		mobileCanvas.style.display = 'none';
	  }
	  isScanning = true;
	  scanBarcode();
	}, 1000);
}

videoSelect.onchange = getStream;

function gotDevices(deviceInfos) {
  while (videoSelect.firstChild) {
    videoSelect.removeChild(videoSelect.firstChild);
  }
  for (var i = deviceInfos.length - 1; i >= 0; --i) {
    var deviceInfo = deviceInfos[i];
    var option = document.createElement('option');
    option.value = deviceInfo.deviceId;
    if (deviceInfo.kind === 'videoinput') {
      option.text = deviceInfo.label || 'camera ' +
        (videoSelect.length + 1);
      videoSelect.appendChild(option);
    } else {455
      //console.log('Found one other kind of source/device: ', deviceInfo);
    }
  }
}
function stopScanning() {	
	button1.style.display =  "block";
	button2.style.display =  "none";
	select.style.display =  "none";
	isScanning = false;
	if (window.stream) {
		window.stream.getTracks().forEach(function(track) {
		  track.stop();
		});
	}
}

function getStream() {
  if (window.stream) {
    window.stream.getTracks().forEach(function(track) {
      track.stop();
    });
  }

  var constraints = {
    video: {
      deviceId: {exact: videoSelect.value}
    }
  };

  navigator.mediaDevices.getUserMedia(constraints).
    then(gotStream).catch(handleError);
}

function gotStream(stream) {
  window.stream = stream; // make stream available to console
  videoElement.srcObject = stream;
}

function handleError(error) {
  console.log('Erro: ', error);
}
</script>
<table style=b"order: solid 1px #ccc ;">
        <tr>
            <!--<th class="rounded-company" style="width: 300px">Código do produto</th> -->
            <th  style="width: 40%" class="vender">Produto</th>
            <th  style="width: 20%" class="vender">Valor</th>
            <th  style="width: 40%" class="vender">Quantidade</th>
        </tr>
    <tbody>
   		
        <?php
   			foreach($this->paginator as $key): 
         		//$this->_helper->viewRenderer->setNoRender();
        		$barcodeOptions = array ('text' => 'ZEND-FRAMEWORK', 'barHeight' => 40);
				// No required options
				$rendererOptions = array();
				//$img=Zend_Barcode::render('code39', 'image', $barcodeOptions, $rendererOptions);
 ?>
        <tr>
            <!--  <td><img src='/Produtos/bar/id/<?php echo $key['id_produtos']?>'></img></td>-->
            <td class="vender"><?php echo $key['descricao']; ?></td>
            <td class="vender">R$ <?php printf("%.2f",$key['valor']); ?></td>
            <td id="item<?php echo $i; ?>" class="item">
            	<span class='button-quantidade'>
	            	<img height=40 align="middle" src='/img/icon_less5.gif' id="iconless<?php echo $i?>" onclick="increment_qtd('compra<?php echo $i?>','less',5)"></img>
	            	<img height=40 align="middle" src='/img/icon_less2.gif' id="iconless<?php echo $i?>" onclick="increment_qtd('compra<?php echo $i?>','less',1)"></img>
            	</span>
	            <input height=40 type="number" min='0' max='100' id="compra<?php echo $i?>" name="qtd[]" size="3" class="qtd" autocomplete="off" style="text-align:center; width: 60px" value=0>
	            <span class="button-quantidade">
		            <img height=40 align="middle" src='/img/icon_plus2.gif' id="iconplus<?php echo $i?>" onclick="increment_qtd('compra<?php echo $i?>','plus',1)"></img>
		            <img height=40 align="middle" src='/img/icon_plus5.gif' id="iconplus<?php echo $i?>" onclick="increment_qtd('compra<?php echo $i?>','plus',5)"></img>
	            </span>
	            <input  type="hidden" id="produto<?php echo $i?>" name="produto[]" autocomplete="off" value="<?php echo $key['id_produtos']?>">
	            <input  type="hidden" id="valor<?php echo $i?>" name="valor[]" autocomplete="off" value="<?php echo $key['valor']?>" class="valor">
            </td>
        </tr>
        <?php $i++; endforeach; ?>
    </tbody>
    <tfoot>
    	<tr>
    		<td class="vender" colspan="2" style="text-align:right;"><strong>Total:</strong> </td>
    		<td class="vender" id="valor_total"></td>
    	</tr>
    	<tr>
    		<td class="vender" colspan="2" style="text-align:right;"><strong>Saldo após a compra:</strong> </td>
    		<td class="vender" id="saldo_remanescente"></td>
    	</tr>
    </tfoot>
  
</table>
<br>
<br>
<input type="hidden" name="id_barraca" value="<?php echo $this->barraca?>">
   <input type="submit" value="Efetuar compra" id="confirmar" disabled="disabled" class="vender">
	</form>       
       
<?php }
else {
	
	echo "<h2>Nenhum registro encontrado</h2>";
	
}
   ?>
<br>

 <?php

    if(count($this->paginator) > 15){
  
echo $this->paginationControl($this->paginator, 'all', 'paginator_item.phtml');

 }?>
 <div id="dialog"></div>
 <?php }?>
 </div>
<div class="#conteudo_baixo"></div>