<?php
$auth = Zend_Auth::getInstance ();
$login = $auth->getIdentity();
$permissoes=array(1);
if($auth->hasIdentity() && in_array($login->nivel,$permissoes)){?>
	<h1>Editar Barraca</h1>
	<?php echo $this->form; ?>
    <div class="clearfix"></div>
    <div class="alert-box warning"><span>Alterta: </span>Só altere os campos "Aceita pagamento?" e "Aceita Negativo?" com orientação da equipe de TI</div>
	
<?php }?>