 <?php
 $auth = Zend_Auth::getInstance ();
$login = $auth->getIdentity();
 $permissoes=array(1);
 if($auth->hasIdentity() && in_array($login->nivel,$permissoes)){?>
<h1>Estorno</h1>
<div class="clearfix"></div>
<br>
<?php
if(count($this->paginator) > 0):
?>
<table>
	<thead>
		<tr>
			<th></th>
			<th class="rounded-company">Hora</th>
			<th class="rounded-company">Produto</th>
			<th class="rounded-company">Cartão</th>
			<th class="rounded-company">Valor</th>
		</tr>
	</thead>
	<tbody>
	<?php foreach($this->paginator as $key): ?>
		<a href="<?php echo $this->url(array('action'=>'meusprodutos','controller'=>'Produtos','id_barracas'=>$key['id_barraca']),null,1); ?>"><?php echo utf8_encode($key['nome']); ?></a>
		<tr>
				<td class="listar-simples"><input type="checkbox" name="venda" value="&nbsp;" /></td>
				<td class="listar-simples">&nbsp;</td>
				<td class="listar-simples">&nbsp;</td>
				<td class="listar-simples">&nbsp;</td>
			</tr>
	<?php endforeach; ?>
	</tbody>
</table>

<?php 
else :
	echo "<h1>Nenhum registro encontrado</h1>";
endif;
?>
<br>
<?php
	echo $this->paginationControl($this->paginator, 'all', 'paginator_item.phtml');
 }?>