<?php
 $auth = Zend_Auth::getInstance ();
$login = $auth->getIdentity();
 $permissoes=array(1);
 if($auth->hasIdentity() && in_array($login->nivel,$permissoes)){?>
 <div class="tituloPag">Barraca</div>

<a class="listar" href="<?php echo $this->url(array('action'=>'new','controller'=>'Barraca'),null,1); ?>"> Incluir</a>
<br>
<br>


<div class="clearfix"></div>


<br>
 <?php

    if(count($this->paginator) > 0){
    
    ?>
<table style="width: 600px;border: solid 1px #ccc ;">
    
        <tr>
            <th class="rounded-company" style="width: 250px">Barraca</th>
            <th class="rounded-company" style="width: 250px">A&ccedil;&otilde;es</th>
        </tr>
    
    <tbody>
   
        <?php foreach($this->paginator as $key){ ?>
        <tr>
            <td class="listar-simples"><?php echo $key['nome']; ?></td>
            <td class="listar-simples"><a href="<?php echo $this->url(array('action'=>'edit','controller'=>'Barraca','id_barracas'=>$key['id_barraca']),null,1); ?>">Editar</a>
             | <a href="<?php echo $this->url(array('action'=>'delete','controller'=>'Barraca','id_barracas'=>$key['id_barraca']),null,1); ?>">Deletar</a>
             </td>
        </tr>
        <?php } ?>
       
       
       
    
    </tbody>
  
</table>
<?php }
else {
	
	echo "<h1>Nenhuma Barraca cadastrada</h1>";
	
}
   ?>
<br>

 <?php

    if(count($this->paginator) > 15){
  
echo $this->paginationControl($this->paginator, 'all', 'paginator_item.phtml');

 }}?>