<?php
$auth = Zend_Auth::getInstance ();
$login = $auth->getIdentity();
$permissoes=array(1);
if($auth->hasIdentity() && in_array($login->nivel,$permissoes)){?>
	<h1>Nova Barraca</h1>
	<?php echo $this->form;     ?>
    <div class="clearfix"></div>
    <div class="alert-box warning"><span>Alterta: </span>Só altere o campo "ação" para barracas que necessitam de tratamento especial, conforme orientação da equipe de TI</div>
<?php }?>