<?php
$auth = Zend_Auth::getInstance ();
$login = $auth->getIdentity();
$permissoes=array(1,2,4);
if($auth->hasIdentity() && in_array($login->nivel,$permissoes)){
	$this->headScript()
		->appendFile($this->baseUrl() . '/js/jquery/js/jquery-1.5.1.min.js','text/javascript')
		->appendFile($this->baseUrl() . '/js/jquery/js/jquery-ui-1.8.14.custom.min.js','text/javascript');
		
	$this->headLink()
		->appendStylesheet($this->baseUrl() . '/js/jquery/css/custom-theme/jquery-ui-1.8.14.custom.css');
	
		
	$this->headScript()->captureStart();?>
	 <div class="tituloPag">Cart√µes</div>
<br>
<br>
	<h1>Estorno de valores</h1>
	<script>
	baseUrl = "<?php echo $this->baseUrl(); ?>";
	$(function () {
		var codigo_atual="";
		$("#id_cartao").focus();
		$("#id_estorno").attr('required', 'required').attr('aria-required', 'true');
		$("#id_forma").attr('required', 'required').attr('aria-required', 'true');
		var creditos=parseFloat($("#creditos").val());
		$("#creditos").val('R$ ' + parseFloat($("#creditos").val()).toFixed(2));
		$("#valor").keyup(function(){
				var novo_valor=$("#valor").val().replace(/,/,".");
				novo_valor= novo_valor.replace(/(-|'|"|`|¥|;)/,"");
				$("#valor").val(novo_valor);
				//$("#valor").val().replace(novo_valor);
			if (parseFloat(novo_valor)){
				$("#saldo_futuro").val('R$ ' + parseFloat(parseFloat(creditos) - parseFloat(novo_valor)).toFixed(2));
				$("#confirmar").attr("disabled",false);
				}
			else{
				$("#confirmar").attr("disabled",true);
				$("#saldo_futuro").val(" ");
				}
			});
		setInterval(function() {
			//verifica se o leitor substituiu o codigo sem mudar de campo(ipad)
			if($("#id_cartao").val() != codigo_atual){
				codigo_atual= $("#id_cartao").val();
				$("#id_cartao").trigger('change');
				//$('#alerta').html("<h3>&nbsp;</h3>");
				}
			//Altera o id do status por nome
			if($("#situacao").val() == "0"){
				$("#situacao").val("DisponÔøΩvel")
				}
			if($("#situacao").val() == "1"){
				$("#situacao").val("Em uso")
				}
			if($("#situacao").val() == "2"){
				$("#situacao").val("Desativado")
				}
			if($("#situacao").val() == "Em uso" && parseFloat($("#saldo_futuro").val().replace(/R../,"")) >= 0){
				$("#submit").attr("disabled",false);
				}
			else{
				$("#submit").attr("disabled",true);
				}
			}, 1200);
		$("#id_cartao").change(function () {
			var id = $(this).val().replace(/\D/g,"");
			$('#descricao').val(" ");
			$('#situacao').val(" ");
			$("#submit").attr("disabled",true);
			if (id.length > 7){
			  if (id.length > 8)
			  	id = id.substr(id.length - 9,8);
			  $("#id_cartao").val(id);
			  $.ajax({
				url: baseUrl + '/cartao/portador/id/' + id,
				dataType: 'json',
				async    : false,
			  	success: function(data) {
				  	$('#descricao').val(data[0].descricao);
			  		$('#situacao').val(data[0].status);
			    	//$('span#creditos').html(parseFloat(data[0].creditos).toFixed(2));
			    	//$(".item").find('input').val('');
			    	//alert('Load was performed.');
					}
				});
			}
			else{
				$('#descricao').val(" ");
				$("#situacao").val(" ");
				$("#submit").attr("disabled",true);
				}
		});
		$("form").submit(function () {
			var	retorno = false;
			
			$("#submit").attr("disabled",true);
			retorno= confirma_estorno($("#id_cartao").val(),$("#valor").val());
			
			if (retorno===false)
				$("#submit").attr("disabled",retorno);
			//return false;
			return retorno;
		});
		});
	</script>
	<div ><?php echo $this->mensagem  ?></div>
	<table style="width: 950px">
	</table>
	<?php echo $this->form;
}?>
