<?php
$auth = Zend_Auth::getInstance ();
$login = $auth->getIdentity();
$permissoes=array(1,2,4);
if($auth->hasIdentity() && in_array($login->nivel,$permissoes)){?>

<?php 
$this->headScript()
	->appendFile($this->baseUrl() . '/js/jquery/js/jquery-1.5.1.min.js','text/javascript')
	->appendFile($this->baseUrl() . '/js/jquery/js/jquery-ui-1.8.14.custom.min.js','text/javascript');
	
$this->headLink()
	->appendStylesheet($this->baseUrl() . '/js/jquery/css/custom-theme/jquery-ui-1.8.14.custom.css');

	
$this->headScript()->captureStart();
?>
 <style type="text/css" media="screen">
     .cartaoDenario{
        background-color: green;
     }
 </style>
 <div class="tituloPag">Cartões</div>


<br>
<br>

<form action="<?php $this->url(array("controller"=>"cartao","action"=>"index")) ?>" method="get">
<h2>Informe número do cartão, documento ou nome do portador:</h2><input class="buscar" id="busca" type="text" name="busca" autocomplete="off">
<script>
$(function () {
    $("#busca").focus();
});
</script>

<input class="input-pp" type="submit" value="Buscar">
<div class='cartaoDenario'><h2 style='color:black'> Os cartões com crédito em denário, aparecem destacados em cor verde, como esse texto.</h2></div>
 

</form>
 
<div class="clearfix"><?php echo $this->mensagem  ?>
<?php 
if (isset($_SESSION['ALERTA']) && is_array($_SESSION['ALERTA']))
	foreach ($_SESSION['ALERTA'] as $alerta){
		echo "<h3>{$alerta}</h3><br>";
	}
	unset($_SESSION['ALERTA']);
?></div>
<div id="conteudo_tabela" class="#conteudo_centro">
<br>

 <?php

    if(isset($this->paginator) && count($this->paginator) > 0){
    
    ?>
<table style="width: 950px">
    <thead>
        <tr>
            <th class="rounded-company" style="width: 100px">Número</th>
            <?php if(isset($_REQUEST['busca']) && $_REQUEST['busca']){?>
            <th class="rounded-company" style="width: 100px">Saldo</th>
            <?php }?>
            <th class="rounded-company" style="width: 150px">Portador</th>
            <th class="rounded-company" style="width: 150px">Documento</th>
            <th class="rounded-company" style="width: 100px">Situação</th>
            <th class="rounded-company" style="width: 300px">Ações</th>
            <th class="rounded-company" style="width: 200px">Relatórios</th>
        </tr>
    </thead>
    <tbody>
   
        <?php
		$status=array(0=>'Disponivel', 1 => 'Em uso',2 => 'Desativado');
        foreach($this->paginator as $key): ?>

        <tr class='<?php echo ($key['tem_denario'])? 'cartaoDenario': '';?>'>
            <td class="listar-simples"><?php echo $key['id_cartao']?></td>
            <?php if(isset($_REQUEST['busca']) && $_REQUEST['busca']){?>
            <td class="listar-simples">R$ <?php printf("%.2f",$key['creditos']); ?></td>
            <?php }?>
            <td class="listar-simples"><?php echo $key['descricao']; ?></td>
            <td class="listar-simples"><?php echo $key['documento']; ?></td>
            <td class="listar-simples"><?php echo $status[$key['status']]; ?></td>
        <td class="listar-simples">
        	<?php if ($key['status'] ==1) {
        			#cartao ativo e em uso /relatorios/transacoes?filtro=12345678
        		 	echo '<a href="' . $this->url(array('action'=>'inserircredito','controller'=>'Cartao','id_cartao'=>$key['id_cartao']),null,1).'">Inserir crédito</a>';
                    echo "<br>"; 
                    echo '<a href="' . $this->url(array('action'=>'estorno','controller'=>'Cartao','id_cartao'=>$key['id_cartao']),null,1) .'">Estornar crédito</a>';
                    echo "<br>";
                    echo '<a href="' . $this->url(array('action'=>'vendasbarraca','controller'=>'relatorios','id_barracas'=>'0','id_cartao'=>$key['id_cartao']),null,1).'">Cancelar Vendas</a>';
                    echo "<br>";
                    echo '<a href="' . $this->url(array('action'=>'desativar','controller'=>'Cartao','id_cartao'=>$key['id_cartao'],'s'=>$key['creditos']),null,1).'" onclick="return confirma_desativar(\''.$key['id_cartao'].'\',\''.$key['descricao'].'\',\''.$key['creditos'].'\');">Desativar </a>';    
                    }            	 
            ?>
            </td>
        <td class="listar-simples">
        	<?php if ($key['status'] > 0) {
        			#cartao em uso ou desativado /relatorios/transacoes?filtro=12345678
        		 	echo '<a href="' . $this->url(array('action'=>'transacoesbarraca','controller'=>'relatorios','filtro'=>$key['id_cartao']),null,1).'">Vendas | </a>';
        		 	echo '<a href="' . $this->url(array('action'=>'receita','controller'=>'relatorios','filtro'=>$key['id_cartao']),null,1).'">Créditos</a>';
        			}            	 
            ?>
            </td>

        </tr>
        <?php endforeach; ?>
       
       
       
    
    </tbody>
  
</table>
<?php }
else {
	if (isset($this->paginationControl)){
		echo "<h1>Registro não encontrado</h1>";
		}
	
}
   ?>
<br>

 <?php
if (isset($this->paginationControl)){
	echo $this->paginationControl($this->paginator, 'all', 'paginator_item.phtml');
	}
?>
</div>
<?php }?>